version: "3.3"

services:
  icon-graphql-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      ICON_GRAPHQL_API_MONGODB_URL: "mongodb:27017"
      ICON_GRAPHQL_API_MONGODB_USER: "mongo"
      ICON_GRAPHQL_API_MONGODB_PASS: "changethis"
      ICON_GRAPHQL_API_PORT: "8000"
      ICON_GRAPHQL_API_PREFIX: ""

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: "icon"
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "changethis"

